In [7]:
import pandas as pd

# Add information to uncharacterized sequences

## Onekp

There are tables on https://ftp.cngb.org/pub/gigadb/pub/10.5524/100001_101000/100627/
with descriptions of every sample.

The samples have 4 letter codes, the sequences have this code in their IDs.

### Load the mapping file

In [2]:
onekp_mapping = pd.read_csv('mappings/onekp/onekp_mapping.tsv', sep='~')

In [3]:
onekp_mapping

,record_id,record_description,new_id
0,scaffold-AALA-2002869-Meliosma_cuneifolia,scaffold-AALA-2002869-Meliosma_cuneifolia,onekp_000000
1,scaffold-AALA-2004467-Meliosma_cuneifolia,scaffold-AALA-2004467-Meliosma_cuneifolia,onekp_000001
2,scaffold-AALA-2004469-Meliosma_cuneifolia,scaffold-AALA-2004469-Meliosma_cuneifolia,onekp_000002
3,scaffold-AALA-2009978-Meliosma_cuneifolia,scaffold-AALA-2009978-Meliosma_cuneifolia,onekp_000003
4,scaffold-AALA-2012589-Meliosma_cuneifolia,scaffold-AALA-2012589-Meliosma_cuneifolia,onekp_000004
...,...,...,...
18206,scaffold-KCPT-2014245-Linum_macraei,scaffold-KCPT-2014245-Linum_macraei,onekp_018206
18207,scaffold-KCPT-2014246-Linum_macraei,scaffold-KCPT-2014246-Linum_macraei,onekp_018207
18208,scaffold-KCPT-2014247-Linum_macraei,scaffold-KCPT-2014247-Linum_macraei,onekp_018208
18209,scaffold-KCPT-2021324-Linum_macraei,scaffold-KCPT-2021324-Linum_macraei,onekp_018209
18210,scaffold-KCPT-2027906-Linum_macraei,scaffold-KCPT-2027906-Linum_macraei,onekp_018210

### Load the samples information

#### Samples df

It was necessary to change the file encoding to utf-8.

In [6]:
samples_df = pd.read_csv('mappings/onekp/Sample-List-with-Taxonomy_utf8.csv')

At some point, the separator is changed to tabs instead of commas

In [7]:
samples_df

,1kP_Sample,Clade,Order,Family,Species,Tissue Type;
0,URDJ,Basalmost angiosperms,Amborellales,Amborellaceae,Amborella trichopoda,leaves;
1,WTKZ,Basalmost angiosperms,Nymphaeales,Nymphaeaceae,Nuphar advena,young leaves;
2,PZRT,Basalmost angiosperms,Nymphaeales,Nymphaeaceae,Nymphaea sp.,young leaves;
3,ROAP,Basalmost angiosperms,Austrobaileyales,Schisandraceae (incl. Illiciac.),Illicium parviflorum,leaves;
4,VZCI,Basalmost angiosperms,Austrobaileyales,Schisandraceae (incl. Illiciac.),Illicium floridanum,young leaves;
...,...,...,...,...,...,...
1337,YRMA\tChromista (Algae)\tFucales\tSargassaceae...,NaN,NaN,NaN,NaN,NaN
1338,HFIK\tChromista (Algae)\tFucales\tSargassaceae...,NaN,NaN,NaN,NaN,NaN
1339,JGGD\tChromista (Algae)\tFucales\tSargassacea\...,NaN,NaN,NaN,NaN,NaN
1340,TZJQ\tDinophyceae\tProrocentrales\tProrocentra...,NaN,NaN,NaN,NaN,NaN
1341,UNBZ\tEuglenozoa\tEuglenales\tEuglenacaea\tEug...,NaN,NaN,NaN,NaN,NaN

In [17]:
samples_df[samples_df['1kP_Sample'].apply(lambda x: '\t' in x)]

,1kP_Sample,Clade,Order,Family,Species,Tissue Type;
831,SGTW\tGinkgoales\tGinkgoales\tGinkgoaceae\tGin...,NaN,NaN,NaN,NaN,NaN
832,VDAO\tGnetales\tEphedrales\tEphedraceae\tEphed...,NaN,NaN,NaN,NaN,NaN
833,GTHK\tGnetales\tGnetales\tGnetaceae\tGnetum mo...,NaN,NaN,NaN,NaN,NaN
834,TOXE\tGnetales\tGnetales\tWelwitschiaceae\tWel...,NaN,NaN,NaN,NaN,NaN
835,XZUY\tCycadales\tCycadales\tCycadaceae\tCycas ...,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...
1337,YRMA\tChromista (Algae)\tFucales\tSargassaceae...,NaN,NaN,NaN,NaN,NaN
1338,HFIK\tChromista (Algae)\tFucales\tSargassaceae...,NaN,NaN,NaN,NaN,NaN
1339,JGGD\tChromista (Algae)\tFucales\tSargassacea\...,NaN,NaN,NaN,NaN,NaN
1340,TZJQ\tDinophyceae\tProrocentrales\tProrocentra...,NaN,NaN,NaN,NaN,NaN
1341,UNBZ\tEuglenozoa\tEuglenales\tEuglenacaea\tEug...,NaN,NaN,NaN,NaN,NaN

--> Split the file into two parts

In [265]:
with open('mappings/onekp/Sample-List-with-Taxonomy_utf8.csv', 'r') as in_file, \
        open('mappings/onekp/Sample-List-with-Taxonomy-utf8-part1.csv', 'w') as out_csv, \
        open('mappings/onekp/Sample-List-with-Taxonomy-utf8-part2.tsv', 'w') as out_tsv:
    
    lines = in_file.readlines()
    lines_p1 = lines[:832]
    #lines_p1 = [line.strip()[1:-2] + '\n' if line.startswith('"') else line for line in lines_p2]
    #lines_p1 = [line.strip('\n').lstrip('"').rstrip(';"') +'\n' for line in lines_p1]
    lines_p2 = lines[832:]
    lines_p2 = [line.strip().strip(';').strip('"').strip(',') + '\n' for line in lines_p2]
    
    out_csv.writelines(lines_p1)
    out_tsv.writelines(lines_p2)

##### CSV part

In the csv part of the table, there was problem with quotes in some rows -> updating them

In [281]:
samples_df_p1 = pd.read_csv('mappings/onekp/Sample-List-with-Taxonomy-utf8-part1.csv')

In [282]:
samples_df_p1

,1kP_Sample,Clade,Order,Family,Species,Tissue Type;
0,URDJ,Basalmost angiosperms,Amborellales,Amborellaceae,Amborella trichopoda,leaves;
1,WTKZ,Basalmost angiosperms,Nymphaeales,Nymphaeaceae,Nuphar advena,young leaves;
2,PZRT,Basalmost angiosperms,Nymphaeales,Nymphaeaceae,Nymphaea sp.,young leaves;
3,ROAP,Basalmost angiosperms,Austrobaileyales,Schisandraceae (incl. Illiciac.),Illicium parviflorum,leaves;
4,VZCI,Basalmost angiosperms,Austrobaileyales,Schisandraceae (incl. Illiciac.),Illicium floridanum,young leaves;
...,...,...,...,...,...,...
826,PZAP,Monocots/Commelinids,Poales,Poaceae,Eleusine coracana,flower;
827,YLWW,Monocots/Commelinids,Poales,Poaceae,Uniola paniculata,young leaves;
828,BSTR,Monocots/Commelinids,Poales,Restionaceae,Chondropetalum tectorum,young shoots;
829,PPQR,Monocots/Commelinids,Poales,Typhaceae,Typha angustifolia,leaves;
830,BRUD,Monocots/Commelinids,Poales,Typhaceae,Typha latifolia,leaf and rhizome shoots;

In [284]:
problematic_rows = samples_df_p1[samples_df_p1['1kP_Sample'].apply(lambda x: '"' in x)]

In [304]:
problematic_rows.head()

,1kP_Sample,Clade,Order,Family,Species,Tissue Type;
31,"XSZI,Magnoliids,Piperales,Piperaceae,Peperomia...",NaN,NaN,NaN,NaN,NaN
108,"XSSD,Core Eudicots,Caryophyllales,Amaranthacea...",NaN,NaN,NaN,NaN,NaN
133,"SKNL,Core Eudicots,Caryophyllales,Caryophyllac...",NaN,NaN,NaN,NaN,NaN
138,"FZQN,Core Eudicots,Caryophyllales,Caryophyllac...",NaN,NaN,NaN,NaN,NaN
159,"MRKX,Core Eudicots,Caryophyllales,Phytolaccace...",NaN,NaN,NaN,NaN,NaN

In [305]:
# Remove the problematic rows
samples_df_p1.drop(problematic_rows.index, inplace=True)

In [306]:
# Fix the problematic rows and create a separate df for them
from io import StringIO
data = problematic_rows['1kP_Sample'].tolist()
data_str = '\n'.join(data)
data_io = StringIO(data_str)
df = pd.read_csv(data_io, header=None, names=samples_df_p1.columns,  quotechar='"', escapechar='\\')

In [308]:
# Add the rows back
samples_df_p1 = pd.concat([samples_df_p1, df])

##### TSV part

In [310]:
samples_df_p2 = pd.read_csv('mappings/onekp/Sample-List-with-Taxonomy-utf8-part2.tsv',sep='\t', header=None)

In [311]:
samples_df_p2.columns = samples_df_p1.columns

In [312]:
samples_df_p2

,1kP_Sample,Clade,Order,Family,Species,Tissue Type;
0,SGTW,Ginkgoales,Ginkgoales,Ginkgoaceae,Ginkgo biloba,developing shoots
1,VDAO,Gnetales,Ephedrales,Ephedraceae,Ephedra sinica,shoot
2,GTHK,Gnetales,Gnetales,Gnetaceae,Gnetum montanum,leaves
3,TOXE,Gnetales,Gnetales,Welwitschiaceae,Welwitschia mirabilis,NaN
4,XZUY,Cycadales,Cycadales,Cycadaceae,Cycas micholitzii,leaves
...,...,...,...,...,...,...
506,YRMA,Chromista (Algae),Fucales,Sargassaceae,Sargassum thunbergii,branches and blades
507,HFIK,Chromista (Algae),Fucales,Sargassaceae,Sargassum vachellianum,branches and blades
508,JGGD,Chromista (Algae),Fucales,Sargassacea,Sargassum muticum,branches and leaves
509,TZJQ,Dinophyceae,Prorocentrales,Prorocentraceae,Prorocentrum micans,cells
510,UNBZ,Euglenozoa,Euglenales,Euglenacaea,Euglena sp.,cells

In [313]:
samples_df = pd.concat([samples_df_p1, samples_df_p2])

In [314]:
samples_df

,1kP_Sample,Clade,Order,Family,Species,Tissue Type;
0,URDJ,Basalmost angiosperms,Amborellales,Amborellaceae,Amborella trichopoda,leaves;
1,WTKZ,Basalmost angiosperms,Nymphaeales,Nymphaeaceae,Nuphar advena,young leaves;
2,PZRT,Basalmost angiosperms,Nymphaeales,Nymphaeaceae,Nymphaea sp.,young leaves;
3,ROAP,Basalmost angiosperms,Austrobaileyales,Schisandraceae (incl. Illiciac.),Illicium parviflorum,leaves;
4,VZCI,Basalmost angiosperms,Austrobaileyales,Schisandraceae (incl. Illiciac.),Illicium floridanum,young leaves;
...,...,...,...,...,...,...
506,YRMA,Chromista (Algae),Fucales,Sargassaceae,Sargassum thunbergii,branches and blades
507,HFIK,Chromista (Algae),Fucales,Sargassaceae,Sargassum vachellianum,branches and blades
508,JGGD,Chromista (Algae),Fucales,Sargassacea,Sargassum muticum,branches and leaves
509,TZJQ,Dinophyceae,Prorocentrales,Prorocentraceae,Prorocentrum micans,cells
510,UNBZ,Euglenozoa,Euglenales,Euglenacaea,Euglena sp.,cells

In [315]:
samples_df['Clade'].value_counts()

Clade
Core Eudicots/Rosids             257
Core Eudicots/Asterids           248
Green Algae                      171
Core Eudicots                    119
Conifers                          76
Leptosporangiate Monilophytes     68
Monocots                          66
Basal Eudicots                    58
Monocots/Commelinids              45
Mosses                            41
Chromista (Algae)                 35
Liverworts                        29
Red Algae                         28
Magnoliids                        27
Lycophytes                        22
Hornworts                         14
Eusporangiate Monilophytes        12
Basalmost angiosperms              8
Glaucophyta (Algae)                5
Cycadales                          4
Gnetales                           3
Chloranthales                      2
Ginkgoales                         1
Dinophyceae                        1
Euglenozoa                         1
Name: count, dtype: int64

#### IDs df

In [180]:
ids_df = pd.read_csv('mappings/onekp/NCBI-ENA-Sequence-Identifiers.csv')

In [181]:
ids_df

,Sample Title,Tax_ID,Organism,description,alternative accession-SRA Study,alternative accession-BioSample,Submission,Experiment,Sample,Run,...,Unnamed: 1015,Unnamed: 1016,Unnamed: 1017,Unnamed: 1018,Unnamed: 1019,Unnamed: 1020,Unnamed: 1021,Unnamed: 1022,Unnamed: 1023,Unnamed: 1024
0,URDJ,13333,Amborella trichopoda,NaN,ERP004258,SAMEA2242364,ERA264960,ERX337098,ERS368197,ERR364329,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,WTKZ,77108,Nuphar advena,NaN,ERP004258,SAMEA2242365,ERA264960,ERX337099,ERS368198,ERR364330,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ROAP,13099,Illicium parviflorum,NaN,ERP023948,SAMEA104170161,ERA979340,ERX2099174,ERS1829179,ERR2040117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,VZCI,13098,Illicium floridanum,NaN,ERP023948,SAMEA104170162,ERA979340,ERX2099175,ERS1829180,ERR2040118,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NWMY,124781,Kadsura heteroclita,NaN,ERP004258,SAMEA2242366,ERA264960,ERX337100,ERS368199,ERR364331,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
492,XKVX,1475407,Heliotropium filiforme,NaN,ERP023948,SAMEA104170560,ERA979340,ERX2099573,ERS1829578,ERR2040516,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
493,IPPG,1475407,Heliotropium filiforme,NaN,ERP023948,SAMEA104170561,ERA979340,ERX2099574,ERS1829579,ERR2040517,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
494,ABEH,1799584,Heliotropium greggii,NaN,ERP023948,SAMEA104170562,ERA979340,ERX2099575,ERS1829580,ERR2040518,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
495,NIGS,1799585,Heliotropium karwinskyi,NaN,ERP023948,SAMEA104170563,ERA979340,ERX2099576,ERS1829581,ERR2040519,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,MZOB,168351,Heliotropium mendocinum,NaN,ERP023948,SAMEA104170564,ERA979340,ERX2099577,ERS1829582,ERR2040520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [182]:
ids_df = ids_df[ids_df.columns[:15]]

In [183]:
ids_df = ids_df.drop(['Unnamed: 10', 'Unnamed: 13'], axis=1)

In [184]:
ids_df['Sample Title'].value_counts()

Sample Title
HNCF    2
AXPJ    2
URDJ    1
DXQW    1
VVPY    1
       ..
FYSJ    1
CGGO    1
WOBD    1
SFKQ    1
MZOB    1
Name: count, Length: 495, dtype: int64

In [185]:
# Remove duplicated IDs
ids_df.drop(346, inplace=True)
ids_df.drop(350, inplace=True)

There are rows with values in the column 'Should Be Combined' -> creating rows with the same values except the 'Sample Title' where the id from 'Should Be Combined' is added.

In [186]:
new_rows = ids_df[~ids_df['Should Be Combined'].isna()]

In [187]:
new_rows['Sample Title'] = new_rows['Should Be Combined']

C:\Users\terca\AppData\Local\Temp\ipykernel_3988\2081890299.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_rows['Sample Title'] = new_rows['Should Be Combined']

In [188]:
ids_df = pd.concat([ids_df, new_rows])

In [211]:
ids_df.shape

(608, 13)

There are rows with values in the column 'Sample Title.1' -> creating rows with the same values except the 'Sample Title' where the id from 'Sample Title.1' is added.

In [220]:
new_rows2 = ids_df[~ids_df['Sample Title.1'].isna()]

In [221]:
new_rows2.shape

(194, 13)

In [222]:
new_rows2['Sample Title'] = new_rows2['Sample Title.1']

C:\Users\terca\AppData\Local\Temp\ipykernel_3988\700630445.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_rows2['Sample Title'] = new_rows2['Sample Title.1']

In [223]:
new_rows2[new_rows2.duplicated('Sample Title', keep=False)]

,Sample Title,Tax_ID,Organism,description,alternative accession-SRA Study,alternative accession-BioSample,Submission,Experiment,Sample,Run,0,Sample Title.1,Should Be Combined
0,PZRT,13333,Amborella trichopoda,NaN,ERP004258,SAMEA2242364,ERA264960,ERX337098,ERS368197,ERR364329,3.0,PZRT,AAXJ
1,FAKD,77108,Nuphar advena,NaN,ERP004258,SAMEA2242365,ERA264960,ERX337099,ERS368198,ERR364330,41.0,FAKD,AQZD
2,UDHA,13099,Illicium parviflorum,NaN,ERP023948,SAMEA104170161,ERA979340,ERX2099174,ERS1829179,ERR2040117,54.0,UDHA,ARYD
3,BZMI,13098,Illicium floridanum,NaN,ERP023948,SAMEA104170162,ERA979340,ERX2099175,ERS1829180,ERR2040118,144.0,BZMI,AXNH
4,LKKX,124781,Kadsura heteroclita,NaN,ERP004258,SAMEA2242366,ERA264960,ERX337100,ERS368199,ERR364331,178.0,LKKX,BEKN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,QFND,85190,Delosperma echinatum,NaN,ERP023948,SAMEA104170236,ERA979340,ERX2099249,ERS1829254,ERR2040192,1273.0,QFND,XOZZ
93,YTYU,323182,Cypselea humifusa,NaN,ERP023948,SAMEA104170237,ERA979340,ERX2099250,ERS1829255,ERR2040193,1274.0,YTYU,XQRV
94,RFAD,221166,Sesuvium portulacastrum,NaN,ERP023948,SAMEA104170238,ERA979340,ERX2099251,ERS1829256,ERR2040194,1314.0,RFAD,XVRU
95,LLEN,115629,Sesuvium verrucosum,NaN,ERP023948,SAMEA104170239,ERA979340,ERX2099252,ERS1829257,ERR2040195,1315.0,LLEN,XWDM
96,VKVG,115629,Sesuvium verrucosum,NaN,ERP023948,SAMEA104170240,ERA979340,ERX2099253,ERS1829258,ERR2040196,1323.0,VKVG,YFQX

In [224]:
new_rows2[new_rows2['Sample Title'] == 'LLEN']

,Sample Title,Tax_ID,Organism,description,alternative accession-SRA Study,alternative accession-BioSample,Submission,Experiment,Sample,Run,0,Sample Title.1,Should Be Combined
95,LLEN,115629,Sesuvium verrucosum,NaN,ERP023948,SAMEA104170239,ERA979340,ERX2099252,ERS1829257,ERR2040195,1315.0,LLEN,XWDM
95,LLEN,115629,Sesuvium verrucosum,NaN,ERP023948,SAMEA104170239,ERA979340,ERX2099252,ERS1829257,ERR2040195,1315.0,LLEN,XWDM

In [225]:
new_rows2[new_rows2['Sample Title'] == 'LLEN'].drop_duplicates()

,Sample Title,Tax_ID,Organism,description,alternative accession-SRA Study,alternative accession-BioSample,Submission,Experiment,Sample,Run,0,Sample Title.1,Should Be Combined
95,LLEN,115629,Sesuvium verrucosum,NaN,ERP023948,SAMEA104170239,ERA979340,ERX2099252,ERS1829257,ERR2040195,1315.0,LLEN,XWDM

In [227]:
new_rows2 = new_rows2.drop_duplicates()

In [229]:
new_rows2.shape

(97, 13)

In [228]:
new_rows2['Sample Title'].nunique()

97

In [230]:
ids_df2 = pd.concat([ids_df, new_rows2])

In [231]:
ids_df2.shape

(705, 13)

In [233]:
ids_df2['Sample Title'].nunique()

705

## Extract the onekp ID

In [55]:
onekp_mapping['onekp_id'] = onekp_mapping['record_id'].apply(lambda x: x.split('-')[1])

In [56]:
onekp_mapping

,record_id,record_description,new_id,onekp_id
0,scaffold-AALA-2002869-Meliosma_cuneifolia,scaffold-AALA-2002869-Meliosma_cuneifolia,onekp_000000,AALA
1,scaffold-AALA-2004467-Meliosma_cuneifolia,scaffold-AALA-2004467-Meliosma_cuneifolia,onekp_000001,AALA
2,scaffold-AALA-2004469-Meliosma_cuneifolia,scaffold-AALA-2004469-Meliosma_cuneifolia,onekp_000002,AALA
3,scaffold-AALA-2009978-Meliosma_cuneifolia,scaffold-AALA-2009978-Meliosma_cuneifolia,onekp_000003,AALA
4,scaffold-AALA-2012589-Meliosma_cuneifolia,scaffold-AALA-2012589-Meliosma_cuneifolia,onekp_000004,AALA
...,...,...,...,...
18206,scaffold-KCPT-2014245-Linum_macraei,scaffold-KCPT-2014245-Linum_macraei,onekp_018206,KCPT
18207,scaffold-KCPT-2014246-Linum_macraei,scaffold-KCPT-2014246-Linum_macraei,onekp_018207,KCPT
18208,scaffold-KCPT-2014247-Linum_macraei,scaffold-KCPT-2014247-Linum_macraei,onekp_018208,KCPT
18209,scaffold-KCPT-2021324-Linum_macraei,scaffold-KCPT-2021324-Linum_macraei,onekp_018209,KCPT
18210,scaffold-KCPT-2027906-Linum_macraei,scaffold-KCPT-2027906-Linum_macraei,onekp_018210,KCPT

In [316]:
onekp_mapping1 = onekp_mapping.merge(samples_df, how='left', left_on='onekp_id', right_on='1kP_Sample')

In [317]:
onekp_mapping1.shape

(18211, 10)

For 16,533 sequences, it was possible to map the information from samples_df, for 1,678 it was not succesuful.

In [318]:
onekp_mapping1[~onekp_mapping1['1kP_Sample'].isna()].shape[0]

16533

In [319]:
onekp_mapping1[onekp_mapping1['1kP_Sample'].isna()].shape[0]

1678

In [321]:
onekp_mapping2 = onekp_mapping1.merge(ids_df, how='left', left_on='onekp_id', right_on='Sample Title')

In [322]:
# entries which were not mapped using either of tables
missing_anno = onekp_mapping2[onekp_mapping2['1kP_Sample'].isna() & onekp_mapping2['Sample Title'].isna()]

1 ID is still missing annotations - ZIWB

In [365]:
missing_anno.index

Index([8938, 8939, 8940], dtype='int64')

Manually add the annotation from https://www.ebi.ac.uk/biosamples/samples/SAMEA5881940

In [369]:
for i in missing_anno.index:
    onekp_mapping2.at[i, '1kP_Sample'] = 'ZIWB'
    onekp_mapping2.at[i, 'Species'] = 'Passiflora sp.'
    onekp_mapping2.at[i, 'Tissue Type;'] = 'leaves and young flowers'
    onekp_mapping2.at[i, 'Tax_ID'] = '2602389'
    onekp_mapping2.at[i, 'Order'] = 'Malpighiales'
    onekp_mapping2.at[i, 'Clade'] = 'Core Eudicots/Rosids'
    onekp_mapping2.at[i, 'Family'] = 'Passifloraceae'

In [372]:
onekp_mapping2.to_csv('mappings/onekp/onekp_mapping_annotated.csv')

## Add tax id lineage info

In [9]:
import os

In [25]:
import taxoniq

In [26]:
import numpy as np

In [11]:
os.chdir('mappings/onekp')

In [15]:
anno_df = pd.read_csv('onekp_mapping_annotated.csv', index_col=0)

In [17]:
anno_df.columns

Index(['record_id', 'record_description', 'new_id', 'onekp_id', '1kP_Sample',
       'Clade', 'Order', 'Family', 'Species', 'Tissue Type;', 'Sample Title',
       'Tax_ID', 'Organism', 'description', 'alternative accession-SRA Study',
       'alternative accession-BioSample', 'Submission', 'Experiment', 'Sample',
       'Run', '0', 'Sample Title.1', 'Should Be Combined'],
      dtype='object')

In [91]:
def add_organism_col(x):
    if type(x['Species']) != float:
        return x['Species'].strip()
    else:
        return x['Organism'].strip()

In [92]:
anno_df['organism'] = anno_df.apply(lambda x: add_organism_col(x), axis=1)

In [93]:
anno_df['organism'].value_counts().head(20)

organism
Eschscholzia californica    176
Papaver somniferum          166
Papaver rhoeas              155
Argemone mexicana           112
Eleusine coracana            87
Aextoxicon punctatum         79
Papaver bracteatum           75
Hakea prostrata              70
Oenothera grandis            67
Oenothera laciniata          64
Uvaria microcarpa            60
Aerva persica                60
Oenothera gaura              59
Papaver setigerum            58
Heliotropium calcicola       56
Phaeoceros carolinianus      54
Euptelea pleiosperma         54
Canella winterana            54
Myristica fragrans           52
Oenothera grandiflora        51
Name: count, dtype: int64

In [11]:
from math import isnan

In [57]:
missing_map = {'Anthemis tinctoria': 99028,
               'Salvia spp.': 21880,
               'Senecio rowleyanus': 189246,
               'Myodocarpus sp.': 2602349,
               'Pogostemon sp.': 2602340,
               'Psychotria ipecacuanha':77880,
               'Micromeria fruticosa':306389,
               'Neocallitropsis pancheri':89193,
               'Talinum sp.':107600,
               'Buddleja sp.':2602345,
               'Salvadora sp.':4325,
               'Heliotropium texanum':1799588,
               'Rosmarinus officinalis':39367,
               'Pseudotsuga wilsoniana':71408,
               'Phyllanthus sp.':2602390,
               'Conyza canadensis':72917,
               'Orobanche fasciculata':48537,
               'Solenostemon scutellarioides':4142,
               'Sanchezia sp.':2602338,
               'Heliconia sp.':4653,
               'Heracleum lanatum':40918,
               'Tabebuia umbellata':1799634,
               'Ilex sp.':4295,
               'Paraneurachne muelleri':1056880,
               'Solanum xanthocarpum':223891,
               'Symphoricarpos sp.':2602352,
               'Impatiens balsamifera':63779,
               'Tetraclinis sp.':2602370,
               'Celsia arcturus':39285,
               'Fokienia hodginsii':89191,
               'Sundacarpus amarus':120640,
               'Phlox sp.':2602334,
               'Haemaria discolor':60011,
               'Maianthemum sp.':2602358,
               'Kalanchoe crenato-diagremontiana':23012,
               'Phycella aff. cyrtanthoides':1263224,
               'Heliotropium tenellum':1799587,
               'Osmunda sp.':2602378,
               'Nymphaea sp.':2602317,
               'Escallonia sp. cv. Newport':23075,
               'Jacquinia sp.':2602336,
               'Daenikera sp.':2602324,
               'Oxalis sp.':519461,
               'Pittosporum sahnianum':1008928,
               'Triodia aff. bynoei':751725,
               'Masdevallia yuangensis':1526612,
               'Begonia sp.':2602330,
               'Larix speciosa':193047,
               'Canna sp.':2602367,
               'Heliotropium racemosum':1799586,
               'Scaevola mossambicensis':2604135,
               'Scapania nemorosa':41848,
               'Urginea maritima':82070,
               'Peliosanthes minor':261227,
               'Hemerocallis sp.':2602360,
               'Chondropetalum tectorum':311269,
               'Nelumbo sp.':2602319,
               'Bergenia sp.':2602329,
               'Odontosororia sp.':2602392,
               'Phymatosorus grossus':253764,
               'Osmunda javanica':90695,
               'Marattia attenuata':167731,
               'Rhodophiala pratensis':232728,
               'Ruscus sp.':2602365,
               'Ludovia sp.':2602354,
               'Hemerocallis spp.':2602360,
               'Davallia fejeensis':328198,
               'Verbascum sp.':2602343,
               'Deparia lobato-crenata':489884,
               'Ptilidium pulcherrimum':2854286,
               'Racomitrium varium':1286318,
               'Isoetes sp.':2602374,
               'Blechnum spicant':114457,
               'Lepidothamnus sp.':2602372,
               'Utricularia sp.':2602341,
               'Curculigo sp.':2602363,
               'Lycopodium annotinum':13840,
               'Malus baccata var. jackii':106549,
               'Anomodon attenuatus':2779804,
               'Sequoiadendron giganteum Glaucum':99814,
               'Ulmus alata alata':24736,
               'Rosulabryum cf. capillare':99387,
               'Schizolaena sp.':2602333,
               'Physcomitrium sp.':2602380,
               'Orthotrichum lyellii':61563,
               'Huperzia squarrosa':73615,
               'Haematococcus pluvialis':44745,
               'Ochlochaete sp.':262510,
               'Azolla cf. caroliniana':39631,
               'Huperzia myrsinites':1799590,
               'Ribes aff. giraldii':175200,
               'Saintpaulia ionantha':85262,
               'Neochloris oleoabundans':1127754,
               'Pellia sp. (cf epiphylla (L.) Corda)':40340,
               'Coccomyxa pringsheimii':248742,
               'Racomitrium elongatum':71396,
               'Cylindrocystis sp.':37306,
               'Helicodictyon planctonicum':138173,
               'Entocladia endozoica':220632,
               'Planophila terrestris':51328,
               'Mollugo spp.':2602321,
               'Pteromonas sp.':52966,
               'Cyathea (Alsophila) spinulosa':204586,
               'Ceratocapnos vesicaria':54430,
               'Chlorococcum microstigmaticum':1538425,
               'Vitreochlamys sp.':78181,
               'Neochloris sp.':3098,
               'Pirula salina':97102,
               'Zygnemopsis sp.':35868,
               'Tetraselmis chui':63592,
               'Nannochloris atomus':133490,
               'Schistochila sp.':2602385,
               'Botryococcus sudeticus':244529,
               'Chlorosarcinopsis halophila':138176,
               'Gonatozygon kinahanii':227148,
               'Scenedesmus dimorphus':119574,
               'Thelypteris acuminata':2137817,
               'Eriospermum lancifolia':1799577,
               'Blasia sp.':2602382,
               'Geminella sp.':163308,
               'Frullania spp.':95763,
               'Microspora cf. tumidula':163316,
               'Chlorella minutissima':3081,
               'Cymbomonas sp.':36880,
               'Staurastrum sebaldi':292362,
               'Pavlova lutheri SAG 926-1':2081491,
               'Spirotaenia sp.':43949,
               'Gracilaria lemaneiformis':2782,
               'Cosmocladium cf. constrictum':184501,
               'Onychonema laeve':184512,
               'Frullania sp.':2602383,
               'Cyanophora paradoxa CCAC 0074 (M0763)':2762,
               'Scourfieldia sp.':163104,
               'Blastophysa cf. rhizopus':619706,
               'Uronema sp.':2047667,
               'Dunaliella viridis dumsii':140095,
               'Staurodesmus omearii':292379,
               'Cyanophora paradoxa CCAC 0091 (M0507/1)':2762,
               'Neosiphonia japonica':2608613,
               'Euastrum affine':485972,
               'Pyropia yezoensis':2788,
               'Neochlorosarcina sp.':332217,
               'Zygnema sp.':43951,
               'Pavlova lutheri CCAC 0028':2081491,
               'Pediastrum duplex CCAC 0147':3105,
               'Pavlova lutheri':2081491
              }

In [58]:
def get_tax_id(x):
    try:
        t = taxoniq.Taxon(scientific_name=x['organism'])
        return t.tax_id
    except:
        if x['organism'] in missing_map.keys():
            return missing_map[x['organism']]
        if isnan(x['Tax_ID']):
            return 'error'
        else:
            return x['Tax_ID']

In [59]:
anno_df['tax_id'] = anno_df.apply(lambda x: get_tax_id(x), axis=1)

In [60]:
anno_df[anno_df['tax_id'] == 'error']['organism'].value_counts()

organism
mixed species              13
Lycopersicon cheesmanii     6
coccoid-prasinophyte        5
unidentified species        4
Name: count, dtype: int64

In [61]:
taxid_map = {323182.0: 2834071, 263337.0: 1630381, 23810.0: 2768810}

In [62]:
def change_tax_ids(x):
    if x in taxid_map.keys():
        return taxid_map[x]
    else:
        return x

In [63]:
anno_df['tax_id'] = anno_df['tax_id'].apply(lambda x: change_tax_ids(x))

In [64]:
def add_lineage(x):
    try:
        t = taxoniq.Taxon(x)
        lineage = dict()
        for line in t.ranked_lineage:
            lineage[line.rank.name] = line.scientific_name
        return lineage
    except:
        return 'error'

In [65]:
anno_df['lineage'] = anno_df['tax_id'].apply(lambda x: add_lineage(x))

In [66]:
def add_line(lineage, line):
    try:
        return lineage[line]
    except:
        return 'unknown'

In [67]:
anno_df['superkingdom'] = anno_df['lineage'].apply(lambda x: add_line(x, 'superkingdom'))

In [68]:
anno_df['kingdom'] = anno_df['lineage'].apply(lambda x: add_line(x, 'kingdom'))

In [69]:
anno_df['phylum'] = anno_df['lineage'].apply(lambda x: add_line(x, 'phylum'))

In [70]:
anno_df['superkingdom'].value_counts()

superkingdom
Eukaryota    18183
unknown         28
Name: count, dtype: int64

In [71]:
anno_df['kingdom'].value_counts()

kingdom
Viridiplantae    17934
unknown            277
Name: count, dtype: int64

In [72]:
anno_df['phylum'].value_counts().head()

phylum
Streptophyta    17315
Chlorophyta       615
unknown           174
Rhodophyta         83
Haptophyta         14
Name: count, dtype: int64

In [73]:
anno_df[anno_df['superkingdom']=='unknown']

,record_id,record_description,new_id,onekp_id,1kP_Sample,Clade,Order,Family,Species,Tissue Type;,...,Run,0,Sample Title.1,Should Be Combined,organism,tax_id,lineage,superkingdom,kingdom,phylum
764,scaffold-AYPS-2011121-unidentified_species,scaffold-AYPS-2011121-unidentified_species,onekp_000764,AYPS,AYPS,Green Algae,incertae sedis,incertae sedis,unidentified species,algal cells,...,NaN,NaN,NaN,NaN,unidentified species,error,error,unknown,unknown,unknown
2459,scaffold-NWQC-2010557-mixed_species,scaffold-NWQC-2010557-mixed_species,onekp_002459,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
2460,scaffold-NWQC-2014685-mixed_species,scaffold-NWQC-2014685-mixed_species,onekp_002460,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
2461,scaffold-NWQC-2014686-mixed_species,scaffold-NWQC-2014686-mixed_species,onekp_002461,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
2462,scaffold-NWQC-2154920-mixed_species,scaffold-NWQC-2154920-mixed_species,onekp_002462,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
2463,scaffold-NWQC-2155553-mixed_species,scaffold-NWQC-2155553-mixed_species,onekp_002463,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
2464,scaffold-NWQC-2158552-mixed_species,scaffold-NWQC-2158552-mixed_species,onekp_002464,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
2465,scaffold-NWQC-2158699-mixed_species,scaffold-NWQC-2158699-mixed_species,onekp_002465,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
6071,scaffold-UGJI-2008423-Lycopersicon_cheesmanii,scaffold-UGJI-2008423-Lycopersicon_cheesmanii,onekp_006071,UGJI,UGJI,Core Eudicots/Asterids,Solanales,Solanaceae,Lycopersicon cheesmanii,leaves;,...,NaN,NaN,NaN,NaN,Lycopersicon cheesmanii,error,error,unknown,unknown,unknown
6072,scaffold-UGJI-2008424-Lycopersicon_cheesmanii,scaffold-UGJI-2008424-Lycopersicon_cheesmanii,onekp_006072,UGJI,UGJI,Core Eudicots/Asterids,Solanales,Solanaceae,Lycopersicon cheesmanii,leaves;,...,NaN,NaN,NaN,NaN,Lycopersicon cheesmanii,error,error,unknown,unknown,unknown
6073,scaffold-UGJI-2011943-Lycopersicon_cheesmanii,scaffold-UGJI-2011943-Lycopersicon_cheesmanii,onekp_006073,UGJI,UGJI,Core Eudicots/Asterids,Solanales,Solanaceae,Lycopersicon cheesmanii,leaves;,...,NaN,NaN,NaN,NaN,Lycopersicon cheesmanii,error,error,unknown,unknown,unknown
6074,scaffold-UGJI-2018781-Lycopersicon_cheesmanii,scaffold-UGJI-2018781-Lycopersicon_cheesmanii,onekp_006074,UGJI,UGJI,Core Eudicots/Asterids,Solanales,Solanaceae,Lycopersicon cheesmanii,leaves;,...,NaN,NaN,NaN,NaN,Lycopersicon cheesmanii,error,error,unknown,unknown,unknown
6075,scaffold-UGJI-2022448-Lycopersicon_cheesmanii,scaffold-UGJI-2022448-Lycopersicon_cheesmanii,onekp_006075,UGJI,UGJI,Core Eudicots/Asterids,Solanales,Solanaceae,Lycopersicon cheesmanii,leaves;,...,NaN,NaN,NaN,NaN,Lycopersicon cheesmanii,error,error,unknown,unknown,unknown
7785,scaffold-XJGM-2003120-coccoid-prasinophyte,scaffold-XJGM-2003120-coccoid-prasinophyte,onekp_007785,XJGM,XJGM,Green Algae,Prasinococcales,Prasinococcaceae,coccoid-prasinophyte,algal cells,...,NaN,NaN,NaN,NaN,coccoid-prasinophyte,error,error,unknown,unknown,unknown
13455,scaffold-AYPS-2000790-unidentified_species,scaffold-AYPS-2000790-unidentified_species,onekp_013455,AYPS,AYPS,Green Algae,incertae sedis,incertae sedis,unidentified species,algal cells,...,NaN,NaN,NaN,NaN,unidentified species,error,error,unknown,unknown,unknown
13456,scaffold-AYPS-2001939-unidentified_species,scaffold-AYPS-2001939-unidentified_species,onekp_013456,AYPS,AYPS,Green Algae,incertae sedis,incertae sedis,unidentified species,algal cells,...,NaN,NaN,NaN,NaN,unidentified species,error,error,unknown,unknown,unknown
13457,scaffold-AYPS-2003014-unidentified_species,scaffold-AYPS-2003014-unidentified_species,onekp_013457,AYPS,AYPS,Green Algae,incertae sedis,incertae sedis,unidentified species,algal cells,...,NaN,NaN,NaN,NaN,unidentified species,error,error,unknown,unknown,unknown
14135,scaffold-NWQC-2001239-mixed_species,scaffold-NWQC-2001239-mixed_species,onekp_014135,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
14136,scaffold-NWQC-2007851-mixed_species,scaffold-NWQC-2007851-mixed_species,onekp_014136,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
14137,scaffold-NWQC-2012632-mixed_species,scaffold-NWQC-2012632-mixed_species,onekp_014137,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
14138,scaffold-NWQC-2015801-mixed_species,scaffold-NWQC-2015801-mixed_species,onekp_014138,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
14139,scaffold-NWQC-2156101-mixed_species,scaffold-NWQC-2156101-mixed_species,onekp_014139,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
14140,scaffold-NWQC-2156955-mixed_species,scaffold-NWQC-2156955-mixed_species,onekp_014140,NWQC,NWQC,Liverworts,Jungermanniales,Plagiochilaceae/Fissidentaceae,mixed species,"gametophyte, possibly some sporophytic tissue",...,NaN,NaN,NaN,NaN,mixed species,error,error,unknown,unknown,unknown
15553,scaffold-UGJI-2002928-Lycopersicon_cheesmanii,scaffold-UGJI-2002928-Lycopersicon_cheesmanii,onekp_015553,UGJI,UGJI,Core Eudicots/Asterids,Solanales,Solanaceae,Lycopersicon cheesmanii,leaves;,...,NaN,NaN,NaN,NaN,Lycopersicon cheesmanii,error,error,unknown,unknown,unknown
16225,scaffold-XJGM-2004374-coccoid-prasinophyte,scaffold-XJGM-2004374-coccoid-prasinophyte,onekp_016225,XJGM,XJGM,Green Algae,Prasinococcales,Prasinococcaceae,coccoid-prasinophyte,algal cells,...,NaN,NaN,NaN,NaN,coccoid-prasinophyte,error,error,unknown,unknown,unknown
16226,scaffold-XJGM-2004717-coccoid-prasinophyte,scaffold-XJGM-2004717-coccoid-prasinophyte,onekp_016226,XJGM,XJGM,Green Algae,Prasinococcales,Prasinococcaceae,coccoid-prasinophyte,algal cells,...,NaN,NaN,NaN,NaN,coccoid-prasinophyte,error,error,unknown,unknown,unknown
16227,scaffold-XJGM-2023064-coccoid-prasinophyte,scaffold-XJGM-2023064-coccoid-prasinophyte,onekp_016227,XJGM,XJGM,Green Algae,Prasinococcales,Prasinococcaceae,coccoid-prasinophyte,algal cells,...,NaN,NaN,NaN,NaN,coccoid-prasinophyte,error,error,unknown,unknown,unknown
16228,scaffold-XJGM-2023143-coccoid-prasinophyte,scaffold-XJGM-2023143-coccoid-prasinophyte,onekp_016228,XJGM,XJGM,Green Algae,Prasinococcales,Prasinococcaceae,coccoid-prasinophyte,algal cells,...,NaN,NaN,NaN,NaN,coccoid-prasinophyte,error,error,unknown,unknown,unknown

In [74]:
anno_df.to_csv('onekp_mapping_annotated_lin2.csv')

In [75]:
import pandas as pd
anno_df = pd.read_csv('onekp_mapping_annotated_lin2.csv', index_col=0)

In [76]:
anno_df

,record_id,record_description,new_id,onekp_id,1kP_Sample,Clade,Order,Family,Species,Tissue Type;,...,Run,0,Sample Title.1,Should Be Combined,organism,tax_id,lineage,superkingdom,kingdom,phylum
0,scaffold-AALA-2002869-Meliosma_cuneifolia,scaffold-AALA-2002869-Meliosma_cuneifolia,onekp_000000,AALA,AALA,Basal Eudicots,Sabiales,Sabiaceae,Meliosma cuneifolia,leaves;,...,ERR2040148,726.0,VVVV,LDEL,Meliosma cuneifolia,400539,"{'species': 'Meliosma cuneifolia', 'genus': 'M...",Eukaryota,Viridiplantae,Streptophyta
1,scaffold-AALA-2004467-Meliosma_cuneifolia,scaffold-AALA-2004467-Meliosma_cuneifolia,onekp_000001,AALA,AALA,Basal Eudicots,Sabiales,Sabiaceae,Meliosma cuneifolia,leaves;,...,ERR2040148,726.0,VVVV,LDEL,Meliosma cuneifolia,400539,"{'species': 'Meliosma cuneifolia', 'genus': 'M...",Eukaryota,Viridiplantae,Streptophyta
2,scaffold-AALA-2004469-Meliosma_cuneifolia,scaffold-AALA-2004469-Meliosma_cuneifolia,onekp_000002,AALA,AALA,Basal Eudicots,Sabiales,Sabiaceae,Meliosma cuneifolia,leaves;,...,ERR2040148,726.0,VVVV,LDEL,Meliosma cuneifolia,400539,"{'species': 'Meliosma cuneifolia', 'genus': 'M...",Eukaryota,Viridiplantae,Streptophyta
3,scaffold-AALA-2009978-Meliosma_cuneifolia,scaffold-AALA-2009978-Meliosma_cuneifolia,onekp_000003,AALA,AALA,Basal Eudicots,Sabiales,Sabiaceae,Meliosma cuneifolia,leaves;,...,ERR2040148,726.0,VVVV,LDEL,Meliosma cuneifolia,400539,"{'species': 'Meliosma cuneifolia', 'genus': 'M...",Eukaryota,Viridiplantae,Streptophyta
4,scaffold-AALA-2012589-Meliosma_cuneifolia,scaffold-AALA-2012589-Meliosma_cuneifolia,onekp_000004,AALA,AALA,Basal Eudicots,Sabiales,Sabiaceae,Meliosma cuneifolia,leaves;,...,ERR2040148,726.0,VVVV,LDEL,Meliosma cuneifolia,400539,"{'species': 'Meliosma cuneifolia', 'genus': 'M...",Eukaryota,Viridiplantae,Streptophyta
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18206,scaffold-KCPT-2014245-Linum_macraei,scaffold-KCPT-2014245-Linum_macraei,onekp_018206,KCPT,KCPT,Core Eudicots/Rosids,Malpighiales,Linaceae,Linum macraei,"stem apex, shoot, leaves;",...,ERR2040379,NaN,NaN,NaN,Linum macraei,586384,"{'species': 'Linum macraei', 'genus': 'Linum',...",Eukaryota,Viridiplantae,Streptophyta
18207,scaffold-KCPT-2014246-Linum_macraei,scaffold-KCPT-2014246-Linum_macraei,onekp_018207,KCPT,KCPT,Core Eudicots/Rosids,Malpighiales,Linaceae,Linum macraei,"stem apex, shoot, leaves;",...,ERR2040379,NaN,NaN,NaN,Linum macraei,586384,"{'species': 'Linum macraei', 'genus': 'Linum',...",Eukaryota,Viridiplantae,Streptophyta
18208,scaffold-KCPT-2014247-Linum_macraei,scaffold-KCPT-2014247-Linum_macraei,onekp_018208,KCPT,KCPT,Core Eudicots/Rosids,Malpighiales,Linaceae,Linum macraei,"stem apex, shoot, leaves;",...,ERR2040379,NaN,NaN,NaN,Linum macraei,586384,"{'species': 'Linum macraei', 'genus': 'Linum',...",Eukaryota,Viridiplantae,Streptophyta
18209,scaffold-KCPT-2021324-Linum_macraei,scaffold-KCPT-2021324-Linum_macraei,onekp_018209,KCPT,KCPT,Core Eudicots/Rosids,Malpighiales,Linaceae,Linum macraei,"stem apex, shoot, leaves;",...,ERR2040379,NaN,NaN,NaN,Linum macraei,586384,"{'species': 'Linum macraei', 'genus': 'Linum',...",Eukaryota,Viridiplantae,Streptophyta
18210,scaffold-KCPT-2027906-Linum_macraei,scaffold-KCPT-2027906-Linum_macraei,onekp_018210,KCPT,KCPT,Core Eudicots/Rosids,Malpighiales,Linaceae,Linum macraei,"stem apex, shoot, leaves;",...,ERR2040379,NaN,NaN,NaN,Linum macraei,586384,"{'species': 'Linum macraei', 'genus': 'Linum',...",Eukaryota,Viridiplantae,Streptophyta

In [79]:
anno_df[['record_id', 'record_description', 'new_id', 'organism', 'tax_id', 'lineage', 'superkingdom', 'kingdom', 'phylum']].to_csv('onekp_mapping_sele.csv')

## Add domains and architecture

In [80]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [81]:
anno_df = pd.read_csv('onekp_mapping_sele.csv', index_col=0)

In [82]:
anno_df.shape

(18211, 9)

In [83]:
archs = pd.read_csv('../../onekp_archs.csv', index_col=0)

In [84]:
archs.shape

(12508, 19)

In [85]:
full_df = archs.merge(anno_df, how='left', left_on='id', right_on='new_id')

In [86]:
full_df.shape

(12508, 28)

In [87]:
full_df['superkingdom'].value_counts()

superkingdom
Eukaryota    12491
unknown         17
Name: count, dtype: int64

In [88]:
full_df['kingdom'].value_counts()

kingdom
Viridiplantae    12337
unknown            171
Name: count, dtype: int64

In [89]:
full_df['phylum'].value_counts()

phylum
Streptophyta         11980
Chlorophyta            355
unknown                111
Rhodophyta              48
Haptophyta               8
Euglenozoa               2
Prasinodermophyta        2
Ciliophora               2
Name: count, dtype: int64

In [90]:
pfam_cols = ['PF06330.14','PF01397.24', 'PF03936.19', 'PF00494.22', 'PF13249.9', 'PF19086.3','PF13243.9']
supfam_cols = ['0041184','0053354', '0053355', '0048261', '0048806', '0046340', '0047573']

In [91]:
full_df['architecture_pfam'].value_counts().head(10)/full_df.shape[0]*100

architecture_pfam
['PF01397.24', 'PF03936.19']                         26.838823
['PF00494.22']                                        7.403262
['PF03936.19']                                        4.844899
['PF01397.24_partial', 'PF03936.19']                  4.253278
['PF13249.9', 'PF13243.9']                            3.557723
['PF13249.9_partial', 'PF13249.9_partial']            1.958746
['PF01397.24', 'PF03936.19_partial']                  1.878798
['PF03936.19_partial']                                1.207227
['PF00494.22', 'PF00494.22_partial']                  1.103294
['PF13243.9_partial', 'PF01397.24', 'PF03936.19']     1.047330
Name: count, dtype: float64

In [92]:
full_df['architecture_supfam'].value_counts().head(10)/full_df.shape[0]*100

architecture_supfam
['0046340']                       38.543332
['0048261']                       18.180365
['0053355']                       10.649185
['0041184', '0053355']             3.237928
['0041184', '0048261']             3.221938
['0046340_partial']                1.095299
['0053354', '0053355']             1.031340
['0053354', '0048261']             0.751519
['0053354', '0048806_partial']     0.735529
['0041184', '0053355_partial']     0.703550
Name: count, dtype: float64

In [93]:
full_df[pfam_cols].sum()/full_df.shape[0]*100

PF06330.14     0.159898
PF01397.24    38.215542
PF03936.19    45.227055
PF00494.22     8.962264
PF13249.9      8.026863
PF19086.3     43.460185
PF13243.9      8.546530
dtype: float64

In [94]:
full_df[supfam_cols].sum()/full_df.shape[0]*100

0041184    40.078350
0053354    40.086345
0053355    45.634794
0048261    44.835305
0048806    81.651743
0046340    85.345379
0047573    79.213303
dtype: float64

In [95]:
full_df.to_csv('../../onekp_annotation.csv')